import { IS_NON_PRODUCTION } from '@utils/environment';

export const FEATURE = {
	OPS_CSV_IMPORT: 'OPS_CSV_IMPORT',
	OPS_MANUAL_DELIVERY: 'OPS_MANUAL_DELIVERY',

	FIN_ONLINE_PAYMENTS: 'FIN_ONLINE_PAYMENTS',
	FIN_MANUAL_PAYMENTS: 'FIN_MANUAL_PAYMENTS',

	UI_DARK_MODE: 'UI_DARK_MODE',

	MAIN_DASHBOARD: 'MAIN_DASHBOARD',
	DASHBOARD_CARE_TEMPLATE: 'DASHBOARD_CARE_TEMPLATE',
	DASHBOARD_ARTICLES: 'DASHBOARD_ARTICLES',
	DASHBOARD_MY_LISTINGS: 'DASHBOARD_MY_LISTINGS',
	DASHBOARD_SERVICES: 'DASHBOARD_SERVICES',
	DASHBOARD_EXPERT_ADVICE: 'DASHBOARD_EXPERT_ADVICE',
	DASHBOARD_ASSIGNED_CARE_PLANS: 'DASHBOARD_ASSIGNED_CARE_PLANS',
	DASHBOARD_EXPERT_PANELS: 'DASHBOARD_EXPERT_PANELS',

	BETA_DASHBOARD: 'BETA_DASHBOARD',
} as const;

export type FeatureName = keyof typeof FEATURE;

export const FEATURE_FLAGS = {
	[FEATURE.OPS_CSV_IMPORT]: true,
	[FEATURE.OPS_MANUAL_DELIVERY]: true,
	[FEATURE.FIN_ONLINE_PAYMENTS]: false,
	[FEATURE.FIN_MANUAL_PAYMENTS]: true,
	[FEATURE.UI_DARK_MODE]: false,

	[FEATURE.MAIN_DASHBOARD]: true,
	[FEATURE.DASHBOARD_CARE_TEMPLATE]: true,
	[FEATURE.DASHBOARD_ARTICLES]: true,
	[FEATURE.DASHBOARD_MY_LISTINGS]: IS_NON_PRODUCTION,
	[FEATURE.DASHBOARD_SERVICES]: true,
	[FEATURE.DASHBOARD_EXPERT_ADVICE]: true,
	[FEATURE.DASHBOARD_ASSIGNED_CARE_PLANS]: true,
	[FEATURE.DASHBOARD_EXPERT_PANELS]: true,

	[FEATURE.BETA_DASHBOARD]: import.meta.env.VITE_ENABLE_BETA === 'true',
} as const;

export const isFeatureEnabled = (feature: FeatureName): boolean => {
	return FEATURE_FLAGS[feature] ?? true;
};

export const Features = {
	isEnabled: (name: FeatureName): boolean => {
		return FEATURE_FLAGS[name];
	},

	getAll: () => FEATURE_FLAGS,
};
