import type { TeamPlayer } from './types';

export const desarrolloPlayers: TeamPlayer[] = [
	{
		id: 'p1',
		fullName: 'Davis Villarreal',
		firstName: 'Davis',
		lastName: 'Villarreal',
		position: ['Pilar', 'apertura', 'centro', 'wing'],
		number: '05',
		imageSrc: '/images/players/Davis_Villarreal.png',
		birthDate: '1997-04-05',
		weight: '66 kg',
		height: '1.60 m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanes Desarrollo',
		cardMetrics: { speed: '6.3mps', reach: '10m' },
		bio: "Originario de Panamá, nacido el 5 de abril de 1997, este profesional de 28 años conjuga su trayectoria corporativa con una prominente carrera en el rugby. Se desempeña como ala en el club Titanes, destacándose por su velocidad y potencia, además de un liderazgo innato. Es propietario de la microempresa Imagine S.A. Holding y se desempeña como tutor de matemáticas y contabilidad desde niveles escolares hasta universitarios. Su mayor inspiración es su padre, un modelo de resiliencia inquebrantable, de quien adoptó la filosofía: 'Los más fuertes se cuidan a sí mismos, pero los más fuertes cuidan a los demás'. Para él, el rugby es una manera de vivir basada en el autocontrol y la familia, con la máxima meta de integrar la selección nacional de Panamá. Profesión: Soy tutor de matemática y contabilidad, tengo una micro empresa y soy ayudante general.",
	},
	{
		id: 'p2',
		fullName: 'Abdiel Zambrano',
		firstName: 'Abdiel',
		lastName: 'Zambrano',
		position: ['medio scrum', 'wing'],
		number: '09',
		imageSrc: '/images/players/Abdiel_Zambrano.png',
		birthDate: '1991-07-17 ',
		weight: '78.9 kg',
		height: '1.60 m',
		experienceYears: '13',
		statuses: ['Jugador'],
		team: 'Titanes Desarrollo',
		cardMetrics: { speed: '7.7mps', reach: '7m' },
		bio: 'Fanatico de los videojuegos , Armador de PCs llegue a titanes despues de probar todos los deportes gracias a mis padres y a partir de ahi no me detuve Profesión: Analista de Soporte IT/coordinador.',
	},
	{
		id: 'p3',
		fullName: 'Kenneth Gutiérrez',
		firstName: 'Kenneth',
		lastName: 'Gutiérrez',
		position: ['Wing'],
		number: '22',
		imageSrc: '/images/players/Kenneth_Gutierrez.png',
		birthDate: '1999-11-03',
		weight: '64.9 kilos',
		height: '1.65m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanes Desarrollo',
		nationalCaps: 0,
		cardMetrics: { speed: '8.2mps', reach: '4.8m', power: '110KG' },
		bio: 'Soy salvadoreña, me encanta mucho el café, amante a los gatos, me gustan los juegos de armar cosas o ordenar cosas y en mis tiempos libres los aprovecho para hacer senderismo. Llegué al Club gracias a que Guerlain me invitó.',
	},
	{
		id: 'p4',
		fullName: 'Jeanpaul Polo',
		firstName: 'Jeanpaul',
		lastName: 'Polo',
		position: ['Pilar'],
		number: '01',
		imageSrc: '/images/players/Jeanpaul_Polo.png',
		birthDate: '2003-05-29',
		weight: '133 kg',
		height: '1.75m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanes Desarrollo',
		nationalCaps: 0,
		cardMetrics: { speed: '5.8mps', reach: '4.7m', power: '210KG' },
		bio: 'El que me conoce sabe que siempre me han gustado los deportes, siempre he jugado distinto tipo de deporte, pero la vida me puso en el camino del rugby lo cual también ha sido importante para mí, tanto como la música, que la música es uno de mis pilares emocionalmente hablando también. Cuando hago algo, me comprometo a hacerlo y hacerlo bien. Me gusta mucho compartir con las personas que me caen bien, son parte de mi entorno. Tengo un humor negro muy oscuro, me gusta ver cosas de terror, películas de terror, me gusta la comedia, las series.',
	},
	{
		id: 'p5',
		fullName: 'David  Maloney', // Completar cuando tengas el nombre
		firstName: 'David',
		lastName: 'Maloney',
		position: ['Medio scrum'],
		number: '09',
		imageSrc: '/images/players/Pendiente_Nombre.png',
		birthDate: '1998-03-30',
		weight: '70 kg',
		height: '1.72m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanes Desarrollo',
		nationalCaps: 0,
		cardMetrics: { speed: '8.3mps', reach: '4.8m', power: '115KG' },
		bio: 'Egresado de la UTP, atento, disciplinado y con ganas de aprender.',
	},
	{
		id: 'p6',
		fullName: 'Gabriel Elizondro ',
		firstName: 'Gabriel',
		lastName: 'Elizondro',
		position: ['Pilar'],
		number: '03',
		imageSrc: '/images/players/Pendiente_Nombre.png',
		birthDate: '1997-11-29',
		weight: '100 kg',
		height: '1.74m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanes Desarrollo',
		nationalCaps: 0,
		cardMetrics: { speed: '6.0mps', reach: '4.9m', power: '185KG' },
		bio: 'Amante a la salchipapa y al patacón relleno y a todo lo positivo y de crecimiento personal.',
	},
];
