import type { TeamPlayer } from './types';

export const femeninoPlayers: TeamPlayer[] = [
	{
		id: 'p1',
		fullName: 'Joselyne Cáceres',
		firstName: 'Joselyne',
		lastName: 'Cáceres',
		position: ['Pilar', 'medio scrum'],
		number: '03',
		imageSrc: '/images/players/Joselyne_Caceres.png',
		birthDate: '2001-09-15',
		weight: '104 kg',
		height: '1.60 m',
		experienceYears: '4',
		statuses: ['Jugador'],
		team: 'Titanides',
		cardMetrics: { speed: '5.6mps', reach: '10m' },
		bio: 'Soy de San Miguelito, siempre me ha gustado los deportes de contacto de hecho al inicio veía mucho fútbol americano ya que era la unico deporte que conocía era rudo, a mis 14 conocí el rugby más no tenía idea que se practicaba en Panamá hasta que a mis 21 años en el 2022 conocí a Loli (Gracias por todo) y me invitó a practicarlo. Como hibbies, amo la música, las películas, jugar Vóleibol y amo jugar rugby. Sueños tengo muchos pero uno en especial es llegar a ser una gran prepadadora física y que mi proyecto crezca. Agradezco a la vida por ser Titanes quien me recibiera y en especial a todos los chicos con los que entrené en mis comienzos, sin ellos no sería quien soy hoy, me hicieron fuerte y me enseñaron el amor y valores del rugby. Hermandad, Honor y Disciplina. Profesión: Estudiante de Lic. Educación física.',
	},
	{
		id: 'p2',
		fullName: 'Vashty Ramos',
		firstName: 'Vashty',
		lastName: 'Ramos',
		position: ['medio scrum'],
		number: '08',
		imageSrc: '/images/players/Vashty_Ramos.png',
		birthDate: '2001-10-05',
		weight: '60 kg',
		height: '1.60 m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 1,
		cardMetrics: { speed: '7.1mps', reach: '5m', power: '30KG' },
		bio: 'Vengo de Veracruz, pueblo costeño. Llegué a Titanes por que una amiga me invitó a un entrenamiento y nunca más me quise ir. Trabajo y estudio en la Ciudad, ahora también el deporte (Rugby) también está acá, me enamoré tanto del deporte que ha sido una de las razones que me impuso a mudarme a la Ciudad. Profesión: Freelancer - Marketing.',
	},
	{
		id: 'p3',
		fullName: 'Chantall Martínez',
		firstName: 'Chantall',
		lastName: 'Martínez',
		position: ['centro'],
		number: '10',
		imageSrc: '/images/players/Chantall_Martinez.png',
		birthDate: '1993-09-06',
		weight: '72.30 kg',
		height: '1.63m',
		experienceYears: '14',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 0,
		cardMetrics: { speed: '7.5mps', reach: '5.2m', power: '135KG' },
		bio: 'Adaptable, un poco sociable, sincera, sarcástica y siempre tengo temas de conversación. Juego de centro pero también puedo abarcar otras posiciones.',
	},
	{
		id: 'p4',
		fullName: 'Sara Avilés ',
		firstName: 'Sara',
		lastName: 'Avilés',
		position: ['Wing'],
		number: '15',
		imageSrc: '/images/players/Sara_Aviles.png',
		birthDate: '2002-10-01',
		weight: '64.9 kg',
		height: '1.65m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 0,
		cardMetrics: { speed: '8.0mps', reach: '4.7m', power: '115KG' },
		bio: 'Soy Salvadoreña, me encanta mucho el café, amante a los gatos, me gusta los juegos de armar cosas o ordenar cosas y en mis tiempos libres los aprovecho para hacer senderismo. Llegué al Club gracias a que Guerlain me invitó.',
	},
	{
		id: 'p5',
		fullName: 'Lourdes Jaén ',
		firstName: 'Lourdes',
		lastName: 'Jaén',
		position: ['Apertura', 'Wing'],
		number: '07',
		imageSrc: '/images/players/Lourdes_Jaen.png',
		birthDate: '1993-05-28',
		weight: '62 kg',
		height: '1.60m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 0,
		cardMetrics: { speed: '7.3mps', reach: '4.9m', power: '112KG' },
		bio: 'Lourdes es una jugadora determinada y con mucha entrega dentro de la cancha. Se caracteriza por su energía, su actitud competitiva y su capacidad de mantenerse firme ante los retos, incluso en los momentos más exigentes del partido. Tiene una personalidad fuerte, alegre y auténtica, siempre dispuesta a apoyar al equipo y a dar el máximo en cada entrenamiento. Como psicóloga, también aporta al equipo empatía, inteligencia emocional y una forma muy humana de conectar con quienes la rodean, equilibrando fortaleza y sensibilidad tanto dentro como fuera del rugby. Para Lourdes, el rugby representa pasión, crecimiento y trabajo en equipo; un espacio donde puede desafiarse, aprender y demostrar que la fuerza también está en la mente y en el corazón.',
	},
	{
		id: 'p6',
		fullName: 'Carla Candanedo',
		firstName: 'Candanedo',
		lastName: 'Apellido',
		position: ['Medio Scrum', 'Wing', 'Centro'],
		number: '04',
		imageSrc: '/images/players/Pendiente_Nombre.png',
		birthDate: '2003-10-28',
		weight: '58.8 kg',
		height: '1.63m',
		experienceYears: '4',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 1,
		cardMetrics: { speed: '8.4mps', reach: '5.2m', power: '110KG' },
		bio: 'Tengo 22 años, actualmente soy estudiante universitaria de la UTP, curso el 3er año en la carrera de Lic. en Mercadeo y Negocios Internacionales. Me considero una persona bastante atlética. Soy súper competitiva, siempre siento que puedo dar mucho más de lo que ya estoy dando.',
	},
	{
		id: 'p7',
		fullName: 'Nathaly Jaramillo ',
		firstName: 'Nathaly',
		lastName: 'Jaramillo',
		position: ['Pilar'],
		number: '01',
		imageSrc: '/images/players/Pendiente_Nombre.png',
		birthDate: '2003-01-23',
		weight: '95 kg',
		height: '1.65m',
		experienceYears: '5',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 1,
		cardMetrics: { speed: '8.4mps', reach: '5.2m', power: '110KG' },
		bio: 'Tengo 22 años, actualmente soy estudiante universitaria de la UTP, curso el 3er año en la carrera de Lic. en Mercadeo y Negocios Internacionales. Me considero una persona bastante atlética. Soy súper competitiva, siempre siento que puedo dar mucho más de lo que ya estoy dando.',
	},
	{
		id: 'p8',
		fullName: 'Yolanda Batista',
		firstName: 'Yolanda',
		lastName: 'Batista',
		position: ['Centro'],
		number: '13',
		imageSrc: '/images/players/Ivonne_Cerceno.png',
		birthDate: '1995-08-03',
		weight: '73.94 kg',
		height: '1.71m',
		experienceYears: '3',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 0,
		cardMetrics: { speed: '7.4mps', reach: '5.2m', power: '140KG' },
		bio: 'Bueno, soy Arquitecta de profesión, soy una persona intro/extrovertida actualmente práctico natación, gym.',
	},
	{
		id: 'p9', // Siguiente registro en la secuencia
		fullName: 'Keithlyn Osorio',
		firstName: 'Keithlyn',
		lastName: 'Osorio',
		position: ['Pilar'],
		number: '02',
		imageSrc: '/images/players/Keithlyn_Osorio.png',
		birthDate: '2000-07-23',
		weight: '77 kg',
		height: '1.68m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 0,
		cardMetrics: { speed: '6.5mps', reach: '4.8m', power: '150KG' },
		bio: 'Jugadora de rugby apasionada por el trabajo en equipo, la disciplina y el crecimiento dentro del deporte. Siempre dispuesta a aprender y dar lo mejor en cada entrenamiento y partido.',
	},
	{
		id: 'p10',
		fullName: 'Andrea Gómez',
		firstName: 'Andrea',
		lastName: 'Gómez',
		position: ['Pilar', 'Apertura', 'Centro'],
		number: '00',
		imageSrc: '/images/players/Andrea_Gomez.png',
		birthDate: '2002-12-31',
		weight: '83 kg',
		height: '1.65m',
		experienceYears: '1.2',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 0,
		cardMetrics: { speed: '7.6mps', reach: '5.1m', power: '155KG' },
		bio: 'Estudio en la UTP ingeniería aeronáutica, trabajo en la UTP como encargada del centro de fotocopiado y la parada UTP, trabajo también en una empresa de neumática, soy de Venezuela llegué a Panamá en 2014, 12 años en Panamá, me gusta casi todos los deportes, ver peli y series, dormir, etc. Llegué a titanides porque los vi entrenar mientras corríamos y un amigo nos invitó a entrar (Guerlain). Sueños hay muchos, desde metas cortas, mediana y largo plazo, van desde ser una buena jugadora, un buen árbitro internacional hasta terminar mi carrera, llegar a ser piloto comercial y lograr todo lo que me proponga en el camino.',
	},
	{
		id: 'p29',
		fullName: 'Kimberly Moreno',
		firstName: 'Kimberly',
		lastName: 'Moreno',
		position: ['Apertura', 'Centro', 'Wing', 'Medio Scrum'],
		number: '15',
		imageSrc: '/images/players/Kimberly_Moreno.png',
		birthDate: '1999-10-15',
		weight: '67 kg',
		height: '1.59m',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanides',
		nationalCaps: 0,
		cardMetrics: { speed: '7.8mps', reach: '4.8m', power: '120KG' },
		bio: 'Soy una persona soñadora, fuerte y auténtica, que disfruta los pequeños momentos y siempre busca crecer mientras sigue brillando a su manera.',
	},
];
