import type { TeamPlayer } from './types';

export const basePlayers: TeamPlayer[] = [
  {
    id: 'p1',
    name: 'Christhoval Barba',
    position: 'Pilar izquierdo',
    number: '04',
    imageSrc: '/images/players/player_1.png',
    birthDate: '1994-08-12',
    height: '6\'1"',
    weight: '102 KG',
    experienceYears: '10',
    strongHand: 'Derecha',
    statuses: ['Capitan', 'Jugador'],
    bio: 'Lider del lineout, fuerte en el contacto y lectura defensiva.',
  },
  {
    id: 'p2',
    name: 'Alberto Cortez',
    position: 'Pilar derecho',
    number: '01',
    imageSrc: '/images/players/player_1.png',
    birthDate: '1997-03-03',
    height: '5\'11"',
    weight: '95 KG',
    experienceYears: '8',
    strongHand: 'Izquierda',
    statuses: ['Sub capitan', 'Jugador'],
    bio: 'Scrum estable y alto volumen de tackles por partido.',
  },
  {
    id: 'p3',
    name: 'Victor Mendez',
    position: 'Hooker',
    number: '02',
    imageSrc: '/images/players/player_1.png',
    birthDate: '1998-10-19',
    height: '5\'10"',
    weight: '98 KG',
    experienceYears: '7',
    strongHand: 'Derecha',
    statuses: ['Jugador'],
    bio: 'Preciso en lanzamiento y agresivo en zonas de ruck.',
  },
  {
    id: 'p4',
    name: 'Luis Navarro',
    position: 'Medio scrum',
    number: '07',
    imageSrc: '/images/players/player_1.png',
    birthDate: '2000-06-07',
    height: '6\'0"',
    weight: '94 KG',
    experienceYears: '6',
    strongHand: 'Derecha',
    statuses: ['Jugador'],
    bio: 'Especialista en breakdown y cobertura lateral.',
  },
  {
    id: 'p5',
    name: 'Carlos Ruiz',
    position: 'Apertura',
    number: '10',
    imageSrc: '/images/players/player_1.png',
    birthDate: '2001-11-28',
    height: '5\'9"',
    weight: '83 KG',
    experienceYears: '5',
    strongHand: 'Derecha',
    statuses: ['Jugador'],
    bio: 'Conductor tactico del equipo y gran vision de juego.',
  },
  {
    id: 'p6',
    name: 'Mateo Reyes',
    position: 'Centro',
    number: '11',
    imageSrc: '/images/players/player_1.png',
    birthDate: '2003-09-14',
    height: '5\'10"',
    weight: '80 KG',
    experienceYears: '4',
    strongHand: 'Izquierda',
    statuses: ['Jugador'],
    bio: 'Velocidad de quiebre y finalizacion en espacios amplios.',
  },
  {
    id: 'p7',
    name: 'Diego Torres',
    position: 'Wing',
    number: '12',
    imageSrc: '/images/players/player_1.png',
    birthDate: '2002-01-22',
    height: '5\'11"',
    weight: '86 KG',
    experienceYears: '5',
    strongHand: 'Derecha',
    statuses: ['Jugador'],
    bio: 'Poderoso en contacto y buena linea de pase en fases rapidas.',
  },
  {
    id: 'p8',
    name: 'Esteban Salas',
    position: 'Pilar izquierdo',
    number: '15',
    imageSrc: '/images/players/player_1.png',
    birthDate: '1999-12-05',
    height: '6\'1"',
    weight: '88 KG',
    experienceYears: '7',
    strongHand: 'Izquierda',
    statuses: ['Jugador', 'Directivo'],
    bio: 'Seguro bajo el juego aereo y lidera la cobertura defensiva.',
  },
  {
    id: 'p9',
    name: 'Raul Castillo',
    position: 'Pilar derecho',
    number: '09',
    imageSrc: '/images/players/player_1.png',
    birthDate: '2004-04-30',
    height: '5\'8"',
    weight: '78 KG',
    experienceYears: '4',
    strongHand: 'Derecha',
    statuses: ['Jugador'],
    bio: 'Distribucion rapida y comunicacion constante con la linea.',
  },
];
