import type { TeamPlayer } from './types';

const basePlayersSeed: TeamPlayer[] = [
	{
		id: 'p1',
		fullName: 'Christhoval Barba',
		firstName: 'Christhoval',
		lastName: 'Barba',
		position: ['Pilar', 'Pilar izquierdo'],
		number: '04',
		imageSrc: '/images/players/Christhoval_Barba.png',
		birthDate: '1994-08-12',
		weight: '106',
		height: '6\'1"',
		experienceYears: '14',
		strongHand: 'Derecha',
		statuses: ['Jugador'],
		nationalCaps: 27,
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '7.4 mps', reach: '17m', power: '135KG', birthYear: '1989' },
		bio: 'Lider del lineout, fuerte en el contacto y lectura defensiva.',
	},
	{
		id: 'p3',
		fullName: 'Joselyne Cáceres',
		firstName: 'Joselyne',
		lastName: 'Cáceres',
		position: ['Prop', 'Hooker', 'Scrum-half'],
		number: '03',
		imageSrc: '/images/players/Joselyne_Caceres.png',
		weight: '104',
		height: '5\'3"',
		experienceYears: '4',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '5.6mps', reach: '10m' },
		bio: 'Soy de San Miguelito, siempre me ha gustado los deportes de contacto de hecho al inicio veía mucho fútbol americano ya que era la unico deporte que conocía era rudo, a mis 14 conocí el rugby más no tenía idea que se practicaba en Panamá hasta que a mis 21 años en el 2022 conocí a Loli (Gracias por todo) y me invitó a practicarlo. Como hibbies, amo la música, las películas, jugar Vóleibol y amo jugar rugby. Sueños tengo muchos pero uno en especial es llegar a ser una gran prepadadora física y que mi proyecto crezca. Agradezco a la vida por ser Titanes quien me recibiera y en especial a todos los chicos con los que entrené en mis comienzos, sin ellos no sería quien soy hoy, me hicieron fuerte y me enseñaron el amor y valores del rugby. Hermandad, Honor y Disciplina. Profesión: Estudiante de Lic. Educación física.',
	},
	{
		id: 'p2',
		fullName: 'Carlos Vigil',
		firstName: 'Carlos',
		lastName: 'Vigil',
		position: ['Hooker'],
		number: '02',
		imageSrc: '/images/players/Christhoval_Barba.png',
		weight: '145',
		height: '5\'10"',
		experienceYears: '13',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { reach: '7' },
		bio: "Vengo desde Arraiján, me. Conocen como 'benny' me gusta mucho los videojuegos y el rugby, también me gusta el ajedrez, me gusta escuchar metal. Profesión: Actualmente estoy en el área de monitoreo de alarmas contra robos e incendios..",
	},
	{
		id: 'p4',
		fullName: 'Angel Bonilla',
		firstName: 'Angel',
		lastName: 'Bonilla',
		position: ['Scrum-half'],
		number: '04',
		imageSrc: '/images/players/Christhoval_Barba.png',
		weight: '61.4',
		height: '5\'5"',
		experienceYears: '0.08',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { reach: '5m' },
		bio: 'Soy de arraiján, me gusta la actividad física como pasatiempos, un día que estaba en la cancha donde practican los vi y le pregunté que deporte era y pues era primera vez que lo escuchaba investigue y me llamó la atención y aquí estoy dando todo de mi en cada entreno Y viajar a suiza Profesión: Trabajo independiente (mantenimiento en barriada).',
	},
	{
		id: 'p5',
		fullName: 'Davis Villarreal',
		firstName: 'Davis',
		lastName: 'Villarreal',
		position: ['Prop', 'Lock', 'Fly Half', 'Center', 'Wing', 'Fullback'],
		number: '05',
		imageSrc: '/images/players/Davis_Villarreal.png',
		weight: '66',
		height: '5\'3"',
		experienceYears: '11 meses',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '6.3mps', reach: '10m' },
		bio: "Originario de Panamá, nacido el 5 de abril de 1997, este profesional de 28 años conjuga su trayectoria corporativa con una prominente carrera en el rugby. Se desempeña como Wing en el club Titanes, destacándose por su velocidad y potencia, además de un liderazgo innato. Es propietario de la microempresa Imagine S.A. Holding y se desempeña como tutor de matemáticas y contabilidad desde niveles escolares hasta universitarios. Su mayor inspiración es su padre, un modelo de resiliencia inquebrantable, de quien adoptó la filosofía: 'Los más fuertes se cuidan a sí mismos, pero los más fuertes cuidan a los demás'. Para él, el rugby es una manera de vivir basada en el autocontrol y la familia, con la máxima meta de integrar la selección nacional de Panamá. Profesión: Soy tutor de matemática y contabilidad, tengo una micro empresa y soy ayudante general.",
	},
	{
		id: 'p6',
		fullName: 'Abdiel Zambrano',
		firstName: 'Abdiel',
		lastName: 'Zambrano',
		position: ['Hooker', 'Scrum-half', 'Wing'],
		number: '06',
		imageSrc: '/images/players/Abdiel_Zambrano.png',
		weight: '78.9',
		height: '5\'3"',
		experienceYears: '13',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '7.7mps', reach: '7m' },
		bio: 'Fanatico de los videojuegos , Armador de PCs llegue a titanes despues de probar todos los deportes gracias a mis padres y a partir de ahi no me detuve Profesión: Analista de Soporte IT/coordinador.',
	},
	{
		id: 'p7',
		fullName: 'Jonathan Naranjo',
		firstName: 'Jonathan',
		lastName: 'Naranjo',
		position: ['Scrum-half', 'Fly Half', 'Center', 'Wing', 'Fullback'],
		number: '07',
		imageSrc: '/images/players/Jonathan_Naranjo.png',
		weight: '80 KG',
		height: '5\'6"',
		experienceYears: '7',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '6.2mps', reach: '20m', power: '95KG' },
		bio: 'Presidente actual del club, llegue por referencia de Furher, fue amor a primera vista con el deporte. Profesión: Ingeniero en Sistemas.',
	},
	{
		id: 'p8',
		fullName: 'Vashty Ramos',
		firstName: 'Vashty',
		lastName: 'Ramos',
		position: ['Scrum-half'],
		number: '08',
		imageSrc: '/images/players/Vashty_Ramos.png',
		weight: '60',
		height: '5\'3"',
		experienceYears: '1',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '7.1mps', reach: '5m', power: '30KG' },
		bio: 'Vengo de Veracruz, pueblo costeño. Llegué a Titanes por que una amiga me invitó a un entrenamiento y nunca más me quise ir. Trabajo y estudio en la Ciudad, ahora también el deporte (Rugby) también está acá, me enamoré tanto del deporte que ha sido una de las razones que me impuso a mudarme a la Ciudad. Profesión: Freelancer - Marketing.',
	},
	{
		id: 'p9',
		fullName: 'Eduardo Hernández',
		firstName: 'Eduardo',
		lastName: 'Hernández',
		position: ['Fly Half', 'Wing'],
		number: '09',
		imageSrc: '/images/players/Eduardo_Hernandez.png',
		weight: '70 kilos',
		height: '5\'6"',
		experienceYears: '1.5',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '7.7mps', reach: '5m', power: '120KG' },
		bio: 'Resido en Cumbre Azul y mi vida ha sido una constante búsqueda de superación. Aunque el fútbol fue mi primer amor, el rugby me dio un propósito distinto. He cumplido el sueño de ser padre y graduarme, pero mi gran meta sigue siendo representar a Panamá en el extranjero y dejar nuestra bandera en lo más alto. Mi historia con el rugby nació en Bocas del Toro y floreció en el club Titanes. Lo que encontré allí fue una hermandad genuina, libre de las rivalidades que a veces empañan otros deportes. Me quedo con la huella de quienes han pasado por mi vida; sus enseñanzas son el motor que me impulsa a seguir creciendo, incluso cuando ya no están presentes. Profesión: trabajo en el servicio nacional aeronaval.',
	},
	{
		id: 'p10',
		fullName: 'Edwin Jiménez',
		firstName: 'Edwin',
		lastName: 'Jiménez',
		position: ['Scrum-half', 'Wing', 'Fullback'],
		number: '10',
		imageSrc: '/images/players/Edwin_Jimenez.png',
		weight: '72',
		height: '5\'6"',
		experienceYears: '3',
		statuses: ['Jugador'],
		team: 'Titanes Rugby Club',
		cardMetrics: { speed: '12.5mps', reach: '10m', power: '100KG' },
		bio: 'Profesión: Estudiante.',
	},
];

const splitFullName = (fullName: string) => {
	const [firstName, ...rest] = fullName.trim().split(/\s+/);
	return { firstName, lastName: rest.join(' ') };
};

export const basePlayers: TeamPlayer[] = basePlayersSeed.map((player) => {
	const names = splitFullName(player.fullName);
	return { ...player, firstName: names.firstName, lastName: names.lastName };
});
