import type { TeamPlayer } from './types';

export const titanesPlayers: TeamPlayer[] = [
	{
		id: 'p1',
		fullName: 'Christhoval Barba',
		firstName: 'Christhoval',
		lastName: 'Barba',
		position: ['Pilar'],
		number: '04',
		imageSrc: '/images/players/Christhoval_Barba.png',
		birthDate: '1994-08-12',
		weight: '106 kg',
		height: '1.85 m',
		experienceYears: '14',
		statuses: ['Jugador'],
		nationalCaps: 27,
		team: 'Titanes',
		cardMetrics: { speed: '7.4 mps', reach: '17m', power: '135KG', birthYear: '1989' },
		bio: 'Lider del lineout, fuerte en el contacto y lectura defensiva.',
	},
	{
		id: 'p2',
		fullName: 'Jonathan Naranjo',
		firstName: 'Jonathan',
		lastName: 'Naranjo',
		position: ['medio scrum', 'apertura', 'centro', 'wing'],
		number: '07',
		imageSrc: '/images/players/Jonathan_Naranjo.png',
		birthDate: '1996-06-27',
		weight: '80 kg',
		height: '1.68 m',
		experienceYears: '7',
		statuses: ['Jugador'],
		team: 'Titanes',
		nationalCaps: 8,
		cardMetrics: { speed: '6.2mps', reach: '20m', power: '95KG' },
		bio: 'Presidente actual del club, llegue por referencia de Furher, fue amor a primera vista con el deporte. Profesión: Ingeniero en Sistemas.',
	},
	{
		id: 'p3',
		fullName: 'Eduardo Hernández',
		firstName: 'Eduardo',
		lastName: 'Hernández',
		position: ['apertura', 'wing'],
		number: '05',
		imageSrc: '/images/players/Eduardo_Hernandez.png',
		birthDate: '1997-04-22',
		weight: '70 kg',
		height: '1.68 m',
		experienceYears: '1.5',
		statuses: ['Jugador'],
		team: 'Titanes',
		nationalCaps: 4,
		cardMetrics: { speed: '7.7mps', reach: '5m', power: '120KG' },
		bio: 'Resido en Cumbre Azul y mi vida ha sido una constante búsqueda de superación. Aunque el fútbol fue mi primer amor, el rugby me dio un propósito distinto. He cumplido el sueño de ser padre y graduarme, pero mi gran meta sigue siendo representar a Panamá en el extranjero y dejar nuestra bandera en lo más alto. Mi historia con el rugby nació en Bocas del Toro y floreció en el club Titanes. Lo que encontré allí fue una hermandad genuina, libre de las rivalidades que a veces empañan otros deportes. Me quedo con la huella de quienes han pasado por mi vida; sus enseñanzas son el motor que me impulsa a seguir creciendo, incluso cuando ya no están presentes. Profesión: trabajo en el servicio nacional aeronaval.',
	},
	{
		id: 'p4',
		fullName: 'Edwin Jiménez',
		firstName: 'Edwin',
		lastName: 'Jiménez',
		position: ['medio scrum', 'wing', 'Apertura', 'Centro'],
		number: '12',
		imageSrc: '/images/players/Edwin_Jimenez.png',
		birthDate: '2002-12-05',
		weight: '73 kg',
		height: '1.70 m',
		experienceYears: '3',
		statuses: ['Jugador'],
		team: 'Titanes',
		cardMetrics: { speed: '12.5mps', reach: '10m', power: '100KG' },
		bio: 'Exatleta regional, exselección nacional de balonmano, exjugador de fútbol, amante del deporte en general, persona multifacética, desarrollador de software junior (Full Stack), creyente, me gusta pasear y viajar. Me caracterizo por ser ambicioso, pero trato de disfrutar de los buenos momentos que me otorga la vida.',
	},
	{
		id: 'p5',
		fullName: 'Caleb Díaz',
		firstName: 'Caleb',
		lastName: 'Martínez',
		position: ['Pilar', 'apertura', 'centro', 'wing'],
		number: '11',
		imageSrc: '/images/players/Caleb_Martinez.png',
		birthDate: '1996-11-24',
		weight: '90 kg',
		height: '1.73 m',
		experienceYears: '3',
		statuses: ['Jugador'],
		team: 'Titanes',
		nationalCaps: 1,
		bio: 'Resido en Panamá y me apasionan los retos constantes. Soy una persona altamente competitiva, pero siempre con la disposición de aprender cosas nuevas y enseñar lo que sé a los demás. Me considero un buen amigo y disfruto hacer de todo un poco, llevando esa misma versatilidad al terreno de juego. En el club Titanes A he encontrado el lugar ideal para desarrollar mi pasión por el rugby y seguir creciendo junto al equipo.',
	},
	{
		id: 'p6',
		fullName: 'Rogerd Moreno',
		firstName: 'Rogerd',
		lastName: 'Moreno',
		position: ['Pilar', 'Wing'],
		number: '01',
		imageSrc: '/images/players/Rogerd_Moreno.png',
		birthDate: '2004-07-01',
		weight: '115 kg',
		height: '1.84m',
		experienceYears: '2',
		statuses: ['Jugador'],
		team: 'Titanes',
		nationalCaps: 1,
		cardMetrics: { speed: '7.0mps', reach: '5.5m', power: '190KG' },
		bio: 'Hola, soy Rogerd Moreno, jugador de rugby para Titanes Rugby Club y me considero que soy destacado por mi fuerza física, trabajo en equipo y mentalidad competitiva, con experiencia compitiendo al más alto nivel nacional en Rugby 7s. Comprometido con la mejora continua tanto dentro como fuera del campo.',
	},
	{
		id: 'p7',
		fullName: 'Jorge Abrego',
		firstName: 'Jorge',
		lastName: 'Abrego',
		position: ['Apertura', 'Wing'],
		number: '00',
		imageSrc: '/images/players/Pendiente_Nombre.png',
		birthDate: '2000-08-25',
		weight: '65 kg',
		height: '1.65m',
		experienceYears: '5',
		statuses: ['Jugador'],
		team: 'Titanes',
		nationalCaps: 0,
		cardMetrics: { speed: '8.5mps', reach: '5.1m', power: '125KG' },
		bio: 'Muy energético, atlético y sumamente competitivo. Me gusta el deporte y ha sido parte de mi vida desde que tengo memoria.',
	},
	{
		id: 'p8',
		fullName: 'Oscar Quezada',
		firstName: 'Oscar',
		lastName: 'Quezada',
		position: ['Pilar'],
		number: '22',
		imageSrc: '/images/players/Oscar_Quezada.png',
		birthDate: '1999-03-22',
		weight: '106 kg',
		height: '1.75m',
		experienceYears: '4',
		statuses: ['Jugador'],
		team: 'Titanes',
		nationalCaps: 1,
		cardMetrics: { speed: '6.9mps', reach: '5.0m', power: '195KG' },
		bio: 'Bueno, conocí el deporte y el club por mi cuenta. Estaba investigando en Instagram sobre otro deporte con banderas y en sugerencias me salió el perfil de Titanes, un mensaje directo y da la casualidad que el día que escribí era un día de práctica, así que sin más tiempo por perder ese mismo día me aparecí, con el único conocimiento que tenía "el nombre del deporte, más nada". Muchos compañeros que ya no practican fueron quienes me enseñaron cada parte del deporte y fui conociendo la familia que es Titanes. Todo ese logro de llegar a selección nacional fue gracias a esas personas que se tomaron unos minutos para explicarme el deporte. Me gustó tanto el deporte que no falté a práctica en ese año. Un año después nació en mi la meta de llegar a selección nacional... con mucho esfuerzo se logra el objetivo asistiendo a los Juegos Bolivarianos del bicentenario Ayacucho 2024, primera participación del rugby en un ciclo olímpico con otros 5 hermanos del club. Ese sueño siguió en pie al año siguiente y se logró ir a un torneo internacional y los juegos centroamericanos Guatemala 2025. Me alegra haber llegado a esta familia por mera casualidad y que forjaron un rugbier más dejando el escudo de Titanes en alto.',
	},
	{
		id: 'p9',
		fullName: 'Asbel Nagakame ',
		firstName: 'Asbel',
		lastName: 'Nagakame',
		position: ['Pilar', 'Centro', 'Wing'],
		number: '10',
		imageSrc: '/images/players/Pendiente_Nombre.png',
		birthDate: '1997-12-30',
		weight: '87.9 kg',
		height: '1.76m',
		experienceYears: '2',
		statuses: ['Jugador', 'Capitán'],
		team: 'Titanes',
		nationalCaps: 1,
		cardMetrics: { speed: '8.6mps', reach: '5.2m', power: '150KG' },
		bio: 'Jugador y capitán enfocado en Rugby 7s, comprometido con liderar mediante el ejemplo. Creo que cada momento tiene su propósito: cuando toca entrenar, se entrena con intensidad; cuando toca compartir con el equipo, se disfruta. Entreno 6 veces por semana entre gimnasio, club y selección nacional, convencido de que la disciplina iguala e incluso supera al talento. Me desempeño como forward por mi fortaleza y como back por mi velocidad, buscando ser un jugador versátil y confiable en cualquier situación de juego.',
	},
	{
		id: 'p10',
		fullName: 'Guerlain Martínez',
		firstName: 'Guerlain',
		lastName: 'Martínez',
		position: ['Apertura', 'Centro', 'Wing'],
		number: '23',
		imageSrc: '/images/players/Guerlain_Martinez.png',
		birthDate: '1998-09-23',
		weight: '80 kg',
		height: '1.75m',
		experienceYears: '2.5',
		statuses: ['Jugador', 'Secretario de la Junta'],
		team: 'Titanes',
		nationalCaps: 1,
		cardMetrics: { speed: '8.5mps', reach: '5.2m', power: '135KG' },
		bio: 'Soy una persona muy comprometida con mi equipo. Disfruto competir y exigirme al máximo dentro de la cancha. Siempre busco aportar al equipo con intensidad, compromiso y buena actitud, tanto en los entrenamientos como en los partidos.',
	},
];
